waiwai-developers/waiwaichan

- logics/pointItem.js
issue: [bugfix: pointItemのwhereが効いていないので修正する #131](https://github.com/waiwai-developers/waiwaichan/issues/131)
> PointItem bug fix

- docker-compose.yml
- entities/translate.js
- logics/pointItem.js
- package.json
- seeders/20241111041901-item.cjs
pull req: [https://github.com/waiwai-developers/waiwaichan/issues/116](https://github.com/waiwai-developers/waiwaichan/issues/116)
> Input seed data

- config copy.json
- repositorys/chatgptapi/ChatGPT.js
- repositorys/deeplapi/translate.mjs
- routes/discordjs/createPoint.js
- routes/discordjs/interaction.js
- routes/discordjs/registration.js
- routes/discordjs/replyRemaind.js
- routes/discordjs/replyThread.js
issue: [feature: 開発環境と本番環境でポイント付与のスタンプを分ける #137](https://github.com/waiwai-developers/waiwaichan/issues/137)
issue: [feature: 開発環境と本番環境でリマインダーの通知の頻度を分ける #138](https://github.com/waiwai-developers/waiwaichan/issues/138)
> Clean settings

- config/commands.json
pull req: [bugfix: helpコマンドキャメルケースになっている #136](https://github.com/waiwai-developers/waiwaichan/issues/136)
> Fix command name

- config/accounts copy.json
- logics/reviewGacha.js
issue: [refactor: config/accounts.jsonを綺麗にしたい #162](https://github.com/waiwai-developers/waiwaichan/issues/162)
> Fix account.json

- routes/discordjs/createPoint.js
issue: [feature: 定数から飴玉を呼んでなかったところがあるので修正する #171](https://github.com/waiwai-developers/waiwaichan/issues/171)
> fix emoji sentence

- .gitignore
- config/commands.json
- config/key copy.json
- docker-compose.yml
- logics/index.js
- logics/minecraftStart.js
- logics/minecraftStop.js
- package-lock.json
- package.json
- repositorys/gcpapi/instanceStart.js
- repositorys/gcpapi/instanceStop.js
- routes/discordjs/interaction.js
- routes/discordjs/registration.js
issue: [feature: Minecraftのサーバーをコマンドから立ち上げられるようにしたい #155](https://github.com/waiwai-developers/waiwaichan/issues/155)
> Add minecraft command

- config/accounts copy.json
- routes/discordjs/interaction.js
pull req: [bugfix: nteraction.replyではなくinteraction.deferReply()を利用する #184](https://github.com/waiwai-developers/waiwaichan/issues/184)
> Use deferReply

- cloudbuild.yaml
Reverts waiwai-developers/waiwaichan#252
> Revert "fix dockerfile path"

- cloudbuild.yaml
> fix dockerfile path

- environment/production/docker-compose.yml
> fix docker-compose

- cloudbuild.yaml
> Fix cloud build json

- cloudbuild.yaml
- createconfig.sh
- environment/development/Dockerfile
- environment/production/docker-compose.yml
> Use deploy docker image

- .sequelizerc
- cloudbuild.yaml
- createconfig.sh
- environment/development/Dockerfile
- environment/production/docker-compose.yml
- nodemon.json
- package.json
- pnpm-lock.yaml
- src/repositories/sequelize-mysql/PointRepositoryImpl.ts
> Release 2024 11 23

- cloudbuild.yaml
> image and container force delete

- src/logics/PullRequestLogic.ts
> Fix review gacha assign filter

- cloudbuild.yaml
> Instead of order docker build

- cloudbuild.yaml
- environment/development/docker-compose.yml
- environment/production/docker-compose.yml
> Fix docker compose and cloud build

- src/logics/PointLogic.ts
> fix: fixed to point draw logic

- config/commands.json
> fix help command

- migrator/migrations/20241128234210-add-column-reminder.ts
- migrator/migrations/20241129184611-add-column-reminder.ts
- src/entities/dto/ReminderDto.ts
- src/entities/vo/ReminderDeletedAt.ts
- src/entities/vo/ReminderStatus.ts
- src/logics/Interfaces/repositories/database/IReminderRepository.ts
- src/logics/Interfaces/repositories/database/IReminderSchedulerRepository.ts
- src/logics/ReminderLogic.ts
- src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
- src/repositories/sequelize-mysql/ReminderSchedulerRepositoryImpl.ts
- src/routes/discordjs/events/SlashCommandRouter.ts
- src/scheduler.ts
> fix remainder rollback

- .nycrc
- environment/development/docker-compose.yml
- environment/production/docker-compose.yml
- migrator/datafixer.ts
- migrator/datafixies/20241203144101-fix-data-user-item.ts
- migrator/datafixies/20241203181803-fix-data-point.ts
- migrator/datafixies/models/DatafixPointModel.ts
- migrator/datafixies/models/DatafixUserItemModel.ts
- migrator/umzug.ts
- package.json
- src/logics/PointLogic.ts
- src/repositories/sequelize-mysql/PointRepositoryImpl.ts
- src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
- src/repositories/sequelize-mysql/ReminderSchedulerRepositoryImpl.ts
- src/repositories/sequelize-mysql/UserPointItemRepositoryImpl.ts
- src/scheduler.di.config.ts
- tests/IntegrationTests/MinecraftCommands.test.ts
- tests/IntegrationTests/TranslateCommands.test.ts
> fix create logic expireAt

- src/repositories/sequelize-mysql/PointRepositoryImpl.ts
> fix countByToday logic

- cloudbuild.yaml
> cloud build options setting

- src/handlers/discord.js/commands/CandyExchangeCommandHandler.ts
- src/routes/discordjs/DiscordCommandRegister.ts
> fix: candychange to candyexchange

- src/entities/vo/DiscordMessageLink.ts
- src/handlers/discord.js/events/CandyReactionHandler.ts
- src/logics/CandyLogic.ts
- src/logics/Interfaces/logics/ICandyLogic.ts
> add message link

- environment/development/Dockerfile
- environment/development/docker-compose.yml
- environment/production/Dockerfile
- environment/production/docker-compose.yml
> fix docker compose base service

- src/entities/vo/ThreadCategoryType.ts
- src/handlers/discord.js/commands/ReviewGachaCommandHandler.ts
- src/logics/PullRequestLogic.ts
> reviewgacha into thread

- src/repositories/sequelize-mysql/CandyRepositoryImpl.ts
> candy limit バグ修正

- src/app.di.config.ts
- src/handlers/discord.js/commands/CandyExchangeCommandHandler.ts
- src/handlers/discord.js/events/ReminderNotifyHandler.ts
- src/logics/CandyLogic.ts
- src/logics/Interfaces/logics/ICandyLogic.ts
- src/logics/Interfaces/repositories/database/ITransaction.ts
- src/logics/Interfaces/repositories/database/IUserCandyItemRepository.ts
- src/logics/ReminderLogic.ts
- src/logics/ThreadLogic.ts
- src/repositories/sequelize-mysql/CandyItemRepositoryImpl.ts
- src/repositories/sequelize-mysql/SequelizeTransaction.ts
- src/repositories/sequelize-mysql/UserCandyItemRepositoryImpl.ts
- src/routes/discordjs/DiscordCommandRegister.ts
- src/scheduler.di.config.ts
> candyの複数個消費対応

- environment/development/docker-compose.yml
- environment/production/docker-compose.yml
> fix: docker compose

- environment/development/docker-compose.yml
- src/entities/constants/Discord.ts
- src/handlers/discord.js/events/AIReplyHandler.ts
- src/handlers/discord.js/events/TranslateReplyHandler.ts
- src/presenter/DiscordTextPresenter.ts
> 2000文字でリプライを分割する

- config/config.json.sample
- src/routes/discordjs/DiscordCommandRegister.ts
> changes to the slash command registration
